# scanner/reports.py
import datetime
import csv
import os
from typing import List, Dict

# The directory where reports will be saved.
REPORTS_DIR = 'reports'

def write_csv(results: List[Dict], host_label: str) -> str:
    os.makedirs(REPORTS_DIR, exist_ok=True)
    ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    fname = f'scan_report_{host_label}_{ts}.csv'
    fpath = os.path.join(REPORTS_DIR, fname)
    keys = ['host', 'port', 'protocol', 'status', 'service']
    with open(fpath, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        for row in sorted(results, key=lambda r: (r['host'], r['port'])):
            writer.writerow(row)
    return fpath


def write_html(results: List[Dict], host_label: str) -> str:
    os.makedirs(REPORTS_DIR, exist_ok=True)
    ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    fname = f'scan_report_{host_label}_{ts}.html'
    fpath = os.path.join(REPORTS_DIR, fname)
    rows = []
    for r in sorted(results, key=lambda r: (r['host'], r['port'])):
        status = r['status']
        cls = 'open' if status == 'open' else 'closed'
        rows.append(f"<tr><td>{r['host']}</td><td>{r['port']}</td><td>{r['protocol']}</td><td class='{cls}'>{status}</td><td>{r['service']}</td></tr>")

    html = f'''<!doctype html>
<html>
<head>
  <meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scan report {host_label}</title>
  <style>
    body{{font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px auto; max-width: 800px; line-height: 1.6; color: #333;}}
    h2{{font-size: 1.5em;}}
    table{{border-collapse: collapse; width: 100%}}
    td, th{{border: 1px solid #ddd; padding: 8px}}
    th{{padding-top: 12px; padding-bottom: 12px; text-align: left; background-color: #4CAF50; color: white;}}
    tr:nth-child(even){{background-color: #f9f9f9}}
    tr:hover{{background-color: #f1f1f1}}
    .open{{color: #28a745; font-weight: bold}}
    .closed{{color: #6c757d}}
    .status-cell {{text-transform: capitalize;}}
    .container{{padding: 2em;}}
    .footer{{text-align: center; margin-top: 2em; color: #777; font-size: 0.9em;}}
  </style>
</head>
<body>
  <div class="container">
    <h2>Scan Report: {host_label}</h2>
    <p>Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    <table>
      <thead><tr><th>Host</th><th>Port</th><th>Protocol</th><th>Status</th><th>Service</th></tr></thead>
      <tbody>
        {''.join(rows)}
      </tbody>
    </table>
    <p class="footer">Generated by Port Scanner</p>
  </div>
</body>
</html>
'''
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(html)
    return fpath
